# Generated by Django 5.0.4 on 2024-04-09 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BinZhou",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_pressure", models.SmallIntegerField()),
                ("out_pressure", models.SmallIntegerField()),
                ("in_flow", models.SmallIntegerField()),
                ("out_flow", models.SmallIntegerField()),
                ("in_temperature", models.SmallIntegerField()),
                ("out_temperature", models.SmallIntegerField()),
                ("detect_time", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "donglin_binzhou",
            },
        ),
        migrations.CreateModel(
            name="DongYing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("out_pressure", models.BigIntegerField()),
                ("out_flow", models.SmallIntegerField()),
                ("out_temperature", models.SmallIntegerField()),
                ("detect_time", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "donglin_dongying",
            },
        ),
        migrations.CreateModel(
            name="LinYi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_pressure", models.BigIntegerField()),
                ("in_flow", models.SmallIntegerField()),
                ("in_temperature", models.SmallIntegerField()),
                ("detect_time", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "donglin_linyi",
            },
        ),
        migrations.CreateModel(
            name="SimulationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.TextField()),
                ("DY", models.TextField()),
                ("BZ", models.TextField()),
                ("LY", models.TextField()),
            ],
            options={
                "db_table": "donglin_simulationhistory",
            },
        ),
    ]
